# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealioApp', '0004_auto_20170225_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='promoFilter',
            fields=[
                ('promotion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dealioApp.Promotion')),
            ],
            bases=('dealioApp.promotion',),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_filtered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rating',
            field=models.CharField(choices=[('Rating:(1-5)', (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')))], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Food Choice', (('American', 'American'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Mexican', 'Mexican'), ('Italian', 'Italian')))], max_length=10),
        ),
    ]
