# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealioApp', '0005_auto_20170324_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promofilter',
            name='promotion_ptr',
        ),
        migrations.DeleteModel(
            name='promoFilter',
        ),
    ]
