# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealioApp', '0006_auto_20170325_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='is_filtered',
        ),
    ]
